apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: earthly-ebs-claim
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 50Gi
