apiVersion: v1
kind: Service
metadata:
  name: earthly
  labels:
    {{- include "earthly-buildkit-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8372
      protocol: TCP
      name: buildkit
  selector:
    {{- include "earthly-buildkit-chart.selectorLabels" . | nindent 4 }}
